import type { Metadata } from "next";
import Sidebar from "@/components/sidebar";
import RightSidebar from "@/components/right-sidebar";
import ProgressCard from "@/components/top-bar";
import { MobileSidebar } from "@/components/mobile-sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="flex">
      <div>
        <Sidebar />
      </div>
      {children}
    </main>
  );
}
