import type { Metadata } from "next";
import Sidebar from "@/components/sidebar";
import RightSidebar from "@/components/right-sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="flex">
      <Sidebar />
      {children}
      <RightSidebar />
    </main>
  );
}
